from pages.base_page import BasePage


class AddMatchForm(BasePage):
    title_bar_header_xpath = "//*[@id='__next']/div[1]/header/div/h6"
    main_page_button_xpath = "//*[@id='__next']/div[1]/div/div/div/ul[1]/div[1]/div[2]/span"
    players_button_xpath = "//*[@id='__next']/div[1]/div/div/div/ul[1]/div[2]/div[2]/span"
    player_account_button_xpath = "//*[@id='__next']/div[1]/div/div/div/ul[2]/div[1]/div[2]/span"
    matches_button_xpath = "//*[@id='__next']/div[1]/div/div/div/ul[2]/div[2]/div[2]/span"
    reports_button_xpath = "//*[@id='__next']/div[1]/div/div/div/ul[2]/div[3]/div[2]/span"
    language_button_xpath = "//*[@id='__next']/div[1]/div/div/div/ul[3]/div[1]/div[2]/span"
    sign_out_button_xpath = "//*[@id='__next']/div[1]/div/div/div/ul[3]/div[2]/div[2]/span"
    my_team_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[1]/div/label"
    my_team_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[1]/div/div/input"
    enemy_team_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[2]/div/label"
    enemy_team_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[2]/div/div/input"
    my_team_score_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[3]/div/label"
    my_team_score_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[3]/div/div/input"
    enemy_team_score_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[4]/div/label"
    enemy_team_score_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[4]/div/div/input"
    date_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[5]/div/label"
    date_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[5]/div/div/input"
    t_shirt_color_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[7]/div/label"
    t_shirt_color_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[7]/div/div/input"
    league_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[8]/div/label"
    league_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[8]/div/div/input"
    time_played_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[9]/div/label"
    time_played_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[9]/div/div/input"
    number_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[10]/div/label"
    number_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[10]/div/div/input"
    web_match_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[11]/div/label"
    web_match_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[11]/div/div/input"
    general_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[12]/div/label"
    general_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[12]/div/div/input"
    rating_label_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[13]/div/label"
    rating_input_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[2]/div/div[13]/div/div/input"
    submit_button_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[3]/button[1]"
    clear_button_xpath = "//*[@id='__next']/div[1]/main/div[2]/form/div[3]/button[2]"
    pass